In [1]:
from FeaturesEngineering.preprocessing import *

data=prepocess_data("data/raw/CreditTraining.csv")
X=data.drop(["Y"],axis=1)
y=data["Y"]

In [6]:
dict_encod={"WOEEncoder":["Educational_Level",'P_Client'],
            
            
        
}

In [7]:
from Models.encoding import *

In [8]:
encoder=encoding(dict_encod)

In [9]:
X_t=encoder.fit_transform(X,y)

In [ ]:
X_t

In [14]:
from FeaturesEngineering.categ_encode import *
enc=Encode(X,y)

SyntaxError: invalid syntax (categ_encode.py, line 117)

In [5]:
var

,Y,Customer_Type,P_Client,Educational_Level,Marital_Status,Number_Of_Dependant,Years_At_Residence,Net_Annual_Income,Years_At_Business,Prod_Sub_Category,Source,Type_Of_Residence,Nb_Of_Products,Prod_Category,join_age,sub_delay,is_closed_date
0,0,Non Existing Client,NP_Client,0.075298,Married,3.0,1,36.0,1.0,C,Sales,Owned,1,B,35,1,0
1,0,Existing Client,P_Client,0.075298,Married,0.0,12,18.0,2.0,C,Sales,Parents,1,G,35,876,0
2,0,Non Existing Client,NP_Client,0.075298,Married,2.0,10,36.0,1.0,C,Sales,Owned,1,B,39,1,0
3,1,Existing Client,NP_Client,0.075298,Married,3.0,3,36.0,1.0,C,Sales,New rent,1,L,29,13,1
4,0,Non Existing Client,NP_Client,0.075298,Married,2.0,1,36.0,1.0,C,Sales,Owned,1,D,59,1,0
5,0,Existing Client,NP_Client,0.075298,Married,0.0,28,60.0,2.0,C,Sales,Old rent,1,C,28,19,0
6,0,Non Existing Client,NP_Client,0.075298,Married,0.0,10,36.0,1.0,C,Sales,Owned,1,B,32,11,0
7,0,Non Existing Client,NP_Client,0.075298,Married,0.0,15,36.0,1.0,C,Sales,Owned,1,B,59,1,1
8,0,Existing Client,NP_Client,0.075298,Single,0.0,0,500.0,3.0,P,Branch,Owned,1,E,27,4059,0
9,1,Existing Client,NP_Client,0.075298,Married,4.0,35,87.0,2.0,C,Sales,Owned,1,L,48,6,1
10,0,Non Existing Client,NP_Client,0.075298,Single,0.0,10,36.0,3.0,C,Sales,Owned,1,B,24,28,0
11,0,Non Existing Client,NP_Client,0.075298,Married,0.0,10,18.0,2.0,C,Sales,Owned,2,B,52,14,0
12,0,Existing Client,P_Client,0.075298,Single,0.0,2,29.0,4.0,C,Branch,Owned,1,G,26,1749,0
13,0,Non Existing Client,NP_Client,0.075298,Married,0.0,15,36.0,1.0,C,Sales,Owned,1,B,25,1,0
14,0,Non Existing Client,NP_Client,0.075298,Married,0.0,1,36.0,1.0,G,Sales,Owned,1,C,37,4,0
15,0,Non Existing Client,NP_Client,0.075298,Married,0.0,10,36.0,1.0,C,Sales,Owned,1,B,42,5,0
16,0,Non Existing Client,NP_Client,0.075298,Married,0.0,15,30.0,1.0,C,Sales,Owned,1,B,38,9,0
17,0,Existing Client,NP_Client,0.075298,Single,0.0,10,18.0,1.0,C,Sales,Owned,1,B,23,166,0
18,1,Non Existing Client,NP_Client,0.075298,Married,2.0,1,36.0,1.0,C,Sales,Owned,1,B,30,3,1
19,0,Non Existing Client,NP_Client,0.075298,Married,3.0,8,18.0,2.0,C,Sales,Owned,1,D,40,3,0
20,0,Non Existing Client,NP_Client,0.075298,Married,0.0,15,30.0,1.0,C,Sales,Owned,1,B,62,21,0
21,0,Non Existing Client,NP_Client,0.075298,Married,0.0,12,31.0,1.0,C,Sales,Owned,1,K,24,20,0
22,0,Non Existing Client,NP_Client,0.075298,Single,0.0,27,26.0,6.0,C,Branch,Owned,1,K,27,15,1
23,0,Existing Client,P_Client,0.075298,Married,3.0,10,24.0,3.0,C,Sales,Owned,1,G,34,1655,0
24,0,Non Existing Client,NP_Client,0.075298,Married,2.0,2,36.0,1.0,C,Sales,Owned,1,B,50,4,0
25,0,Non Existing Client,NP_Client,0.075298,Married,0.0,1,36.0,1.0,C,Sales,Owned,1,B,64,1,0
26,0,Non Existing Client,NP_Client,0.075298,Married,0.0,1,20.0,1.0,C,Sales,Owned,1,D,39,6,0
27,0,Non Existing Client,NP_Client,0.075298,Single,0.0,4,18.0,4.0,C,Sales,Owned,1,B,22,4,0
28,0,Existing Client,NP_Client,0.075298,Married,2.0,10,18.0,2.0,C,Sales,Owned,1,D,45,535,0
29,0,Non Existing Client,NP_Client,0.075298,Married,0.0,22,18.0,2.0,C,Sales,Owned,1,B,59,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5350,0,Non Existing Client,NP_Client,0.075298,Married,2.0,20,48.0,21.0,C,Branch,Owned,1,B,47,35,0
5351,0,Non Existing Client,NP_Client,0.075298,Married,0.0,20,18.0,2.0,C,Branch,Owned,1,D,28,3,0
5352,0,Existing Client,P_Client,0.075298,Married,1.0,29,49.0,3.0,C,Branch,Owned,1,H,25,1149,0
5353,0,Existing Client,NP_Client,0.075298,Married,3.0,22,18.0,2.0,C,Sales,Owned,1,D,29,1032,0
5354,0,Existing Client,NP_Client,0.075298,Single,1.0,20,151.0,5.0,G,Branch,Owned,1,J,27,2232,0
5355,0,Existing Client,NP_Client,0.075298,Married,1.0,20,300.0,10.0,P,Branch,Owned,1,E,37,2574,0
5356,0,Non Existing Client,NP_Client,0.075298,Married,5.0,1,36.0,1.0,C,Sales,Owned,1,B,46,7,0
5357,0,Existing Client,P_Client,0.055769,Married,4.0,10,113.0,1.0,G,Branch,Owned,1,G,51,331,0
5358,0,Non Existing Client,NP_Client,0.075298,Married,0.0,28,20.0,1.0,C,Sales,Old rent,1,B,57,1,0
5359,0,Existing Client,NP_Client,0.075298,Married,0.0,9,1800.0,5.0,P,Branch,Owned,1,E,33,5413,0
5360,0,Non Existing Client,NP_Client,0.075298,Single,0.0,1,20.0,1.0,C,Sales,Owned,1,B,25,8,0
5361,0,Non Existing Client,NP_Client,0.075298,Married,0.0,15,36.0,1.0,C,Sales,Owned,1,B,56,1,0
5362,0,Non Existing Client,NP_Client,0.075298,Married,0.0,1,36.0,1.0,C,Sales,Owned,1,B,32,0,0
5363,0,Existing Client,NP_Client,0.075298,Married,0.0,15,30.0,1.0,C,Sales,Owned,1,B,49,1007,0
5364,0,Existing Client,NP_Client,0.075298,Married,2.0,30,100.0,1.0,P,Branch,Owned,1,E,47,5950,0
5365,0,Non Existing Client,NP_Client,0.075298,Married,0.0,10,18.0,2.0,C,Sales,Owned,1,B,31,4,0
5366,0,Non Existing Client,NP_Client,0.055769,Married,0.0,1,20.0,1.0,C,Branch,Owned,2,C,49,1,1
5367,0,Non Existing Client,NP_Client,0.075298,Married,2.0,10,50.0,10.0,C,Sales,Owned,1,B,48,1,0
5368,0,Non Existing Client,NP_Client,0.075298,Married,1.0,10,36.0,3.0,C,Sales,Owned,1,B,35,1,0
5369,0,Existing Client,P_Client,0.075298,Single,0.0,25,36.0,1.0,C,Sales,Owned,1,D,24,505,0
5370,0,Existing Client,NP_Client,0.075298,Married,0.0,15,36.0,1.0,C,Sales,Owned,1,B,55,2120,0
5371,1,Existing Client,NP_Client,0.055769,Single,0.0,15,50.0,7.0,G,Sales,Owned,1,C,37,29,1
5372,0,Non Existing Client,NP_Client,0.075298,Married,0.0,11,36.0,3.0,C,Sales,Owned,1,B,53,3,0
5373,0,Existing Client,NP_Client,0.075298,Married,3.0,20,50.0,1.0,C,Sales,Owned,1,L,52,7,0
5374,0,Non Existing Client,NP_Client,0.075298,Married,0.0,1,20.0,1.0,C,Sales,Owned,1,B,29,3,0
5375,0,Non Existing Client,NP_Client,0.075298,Married,2.0,1,36.0,1.0,G,Sales,Owned,1,C,35,37,0
5376,1,Existing Client,NP_Client,0.075298,Married,3.0,15,24.0,1.0,C,Sales,Owned,1,L,29,19,1
5377,0,Non Existing Client,NP_Client,0.075298,Divorced,0.0,14,14.0,30.0,C,Branch,Old rent,1,B,61,1,1
5378,0,Non Existing Client,NP_Client,0.075298,Married,1.0,1,36.0,1.0,G,Sales,Owned,1,C,29,4,0
5379,0,Non Existing Client,NP_Client,0.075298,Married,0.0,15,30.0,1.0,C,Sales,Owned,1,B,29,8,0

In [3]:
X["Educational_Level"].unique().tolist()

['University', 'Master/PhD', 'Secondary or Less', 'Diploma']

In [4]:
colums=["Educational_Level"]
# enc.FeatureHasher(3,colums)
dict_args={"Educational_Level":{ 'University':3 ,'Master/PhD':4,'Secondary or Less':1, 'Diploma':2}}
# fh = FeatureHasher(n_features=3, input_type='string')
# hashed_feat=fh.fit_transform(X["P_Client"]).toarray()

In [5]:
enc.frequency_encoding(colums)

,Customer_Type,P_Client,Educational_Level,Marital_Status,Number_Of_Dependant,Years_At_Residence,Net_Annual_Income,Years_At_Business,Prod_Sub_Category,Source,Type_Of_Residence,Nb_Of_Products,Prod_Category,join_age,sub_delay,is_closed_date
0,Non Existing Client,NP_Client,0.889654,Married,3.0,1,36.0,1.0,C,Sales,Owned,1,B,35,1,0
1,Existing Client,P_Client,0.889654,Married,0.0,12,18.0,2.0,C,Sales,Parents,1,G,35,876,0
2,Non Existing Client,NP_Client,0.889654,Married,2.0,10,36.0,1.0,C,Sales,Owned,1,B,39,1,0
3,Existing Client,NP_Client,0.889654,Married,3.0,3,36.0,1.0,C,Sales,New rent,1,L,29,13,1
4,Non Existing Client,NP_Client,0.889654,Married,2.0,1,36.0,1.0,C,Sales,Owned,1,D,59,1,0
5,Existing Client,NP_Client,0.889654,Married,0.0,28,60.0,2.0,C,Sales,Old rent,1,C,28,19,0
6,Non Existing Client,NP_Client,0.889654,Married,0.0,10,36.0,1.0,C,Sales,Owned,1,B,32,11,0
7,Non Existing Client,NP_Client,0.889654,Married,0.0,15,36.0,1.0,C,Sales,Owned,1,B,59,1,1
8,Existing Client,NP_Client,0.889654,Single,0.0,0,500.0,3.0,P,Branch,Owned,1,E,27,4059,0
9,Existing Client,NP_Client,0.889654,Married,4.0,35,87.0,2.0,C,Sales,Owned,1,L,48,6,1
10,Non Existing Client,NP_Client,0.889654,Single,0.0,10,36.0,3.0,C,Sales,Owned,1,B,24,28,0
11,Non Existing Client,NP_Client,0.889654,Married,0.0,10,18.0,2.0,C,Sales,Owned,2,B,52,14,0
12,Existing Client,P_Client,0.889654,Single,0.0,2,29.0,4.0,C,Branch,Owned,1,G,26,1749,0
13,Non Existing Client,NP_Client,0.889654,Married,0.0,15,36.0,1.0,C,Sales,Owned,1,B,25,1,0
14,Non Existing Client,NP_Client,0.889654,Married,0.0,1,36.0,1.0,G,Sales,Owned,1,C,37,4,0
15,Non Existing Client,NP_Client,0.889654,Married,0.0,10,36.0,1.0,C,Sales,Owned,1,B,42,5,0
16,Non Existing Client,NP_Client,0.889654,Married,0.0,15,30.0,1.0,C,Sales,Owned,1,B,38,9,0
17,Existing Client,NP_Client,0.889654,Single,0.0,10,18.0,1.0,C,Sales,Owned,1,B,23,166,0
18,Non Existing Client,NP_Client,0.889654,Married,2.0,1,36.0,1.0,C,Sales,Owned,1,B,30,3,1
19,Non Existing Client,NP_Client,0.889654,Married,3.0,8,18.0,2.0,C,Sales,Owned,1,D,40,3,0
20,Non Existing Client,NP_Client,0.889654,Married,0.0,15,30.0,1.0,C,Sales,Owned,1,B,62,21,0
21,Non Existing Client,NP_Client,0.889654,Married,0.0,12,31.0,1.0,C,Sales,Owned,1,K,24,20,0
22,Non Existing Client,NP_Client,0.889654,Single,0.0,27,26.0,6.0,C,Branch,Owned,1,K,27,15,1
23,Existing Client,P_Client,0.889654,Married,3.0,10,24.0,3.0,C,Sales,Owned,1,G,34,1655,0
24,Non Existing Client,NP_Client,0.889654,Married,2.0,2,36.0,1.0,C,Sales,Owned,1,B,50,4,0
25,Non Existing Client,NP_Client,0.889654,Married,0.0,1,36.0,1.0,C,Sales,Owned,1,B,64,1,0
26,Non Existing Client,NP_Client,0.889654,Married,0.0,1,20.0,1.0,C,Sales,Owned,1,D,39,6,0
27,Non Existing Client,NP_Client,0.889654,Single,0.0,4,18.0,4.0,C,Sales,Owned,1,B,22,4,0
28,Existing Client,NP_Client,0.889654,Married,2.0,10,18.0,2.0,C,Sales,Owned,1,D,45,535,0
29,Non Existing Client,NP_Client,0.889654,Married,0.0,22,18.0,2.0,C,Sales,Owned,1,B,59,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5350,Non Existing Client,NP_Client,0.889654,Married,2.0,20,48.0,21.0,C,Branch,Owned,1,B,47,35,0
5351,Non Existing Client,NP_Client,0.889654,Married,0.0,20,18.0,2.0,C,Branch,Owned,1,D,28,3,0
5352,Existing Client,P_Client,0.889654,Married,1.0,29,49.0,3.0,C,Branch,Owned,1,H,25,1149,0
5353,Existing Client,NP_Client,0.889654,Married,3.0,22,18.0,2.0,C,Sales,Owned,1,D,29,1032,0
5354,Existing Client,NP_Client,0.889654,Single,1.0,20,151.0,5.0,G,Branch,Owned,1,J,27,2232,0
5355,Existing Client,NP_Client,0.889654,Married,1.0,20,300.0,10.0,P,Branch,Owned,1,E,37,2574,0
5356,Non Existing Client,NP_Client,0.889654,Married,5.0,1,36.0,1.0,C,Sales,Owned,1,B,46,7,0
5357,Existing Client,P_Client,0.096762,Married,4.0,10,113.0,1.0,G,Branch,Owned,1,G,51,331,0
5358,Non Existing Client,NP_Client,0.889654,Married,0.0,28,20.0,1.0,C,Sales,Old rent,1,B,57,1,0
5359,Existing Client,NP_Client,0.889654,Married,0.0,9,1800.0,5.0,P,Branch,Owned,1,E,33,5413,0
5360,Non Existing Client,NP_Client,0.889654,Single,0.0,1,20.0,1.0,C,Sales,Owned,1,B,25,8,0
5361,Non Existing Client,NP_Client,0.889654,Married,0.0,15,36.0,1.0,C,Sales,Owned,1,B,56,1,0
5362,Non Existing Client,NP_Client,0.889654,Married,0.0,1,36.0,1.0,C,Sales,Owned,1,B,32,0,0
5363,Existing Client,NP_Client,0.889654,Married,0.0,15,30.0,1.0,C,Sales,Owned,1,B,49,1007,0
5364,Existing Client,NP_Client,0.889654,Married,2.0,30,100.0,1.0,P,Branch,Owned,1,E,47,5950,0
5365,Non Existing Client,NP_Client,0.889654,Married,0.0,10,18.0,2.0,C,Sales,Owned,1,B,31,4,0
5366,Non Existing Client,NP_Client,0.096762,Married,0.0,1,20.0,1.0,C,Branch,Owned,2,C,49,1,1
5367,Non Existing Client,NP_Client,0.889654,Married,2.0,10,50.0,10.0,C,Sales,Owned,1,B,48,1,0
5368,Non Existing Client,NP_Client,0.889654,Married,1.0,10,36.0,3.0,C,Sales,Owned,1,B,35,1,0
5369,Existing Client,P_Client,0.889654,Single,0.0,25,36.0,1.0,C,Sales,Owned,1,D,24,505,0
5370,Existing Client,NP_Client,0.889654,Married,0.0,15,36.0,1.0,C,Sales,Owned,1,B,55,2120,0
5371,Existing Client,NP_Client,0.096762,Single,0.0,15,50.0,7.0,G,Sales,Owned,1,C,37,29,1
5372,Non Existing Client,NP_Client,0.889654,Married,0.0,11,36.0,3.0,C,Sales,Owned,1,B,53,3,0
5373,Existing Client,NP_Client,0.889654,Married,3.0,20,50.0,1.0,C,Sales,Owned,1,L,52,7,0
5374,Non Existing Client,NP_Client,0.889654,Married,0.0,1,20.0,1.0,C,Sales,Owned,1,B,29,3,0
5375,Non Existing Client,NP_Client,0.889654,Married,2.0,1,36.0,1.0,G,Sales,Owned,1,C,35,37,0
5376,Existing Client,NP_Client,0.889654,Married,3.0,15,24.0,1.0,C,Sales,Owned,1,L,29,19,1
5377,Non Existing Client,NP_Client,0.889654,Divorced,0.0,14,14.0,30.0,C,Branch,Old rent,1,B,61,1,1
5378,Non Existing Client,NP_Client,0.889654,Married,1.0,1,36.0,1.0,G,Sales,Owned,1,C,29,4,0
5379,Non Existing Client,NP_Client,0.889654,Married,0.0,15,30.0,1.0,C,Sales,Owned,1,B,29,8,0

In [11]:
import pandas as pd
pd.concat([X,pd.DataFrame(hashed_feat)],axis=1)

,Customer_Type,P_Client,Educational_Level,Marital_Status,Number_Of_Dependant,Years_At_Residence,Net_Annual_Income,Years_At_Business,Prod_Sub_Category,Source,Type_Of_Residence,Nb_Of_Products,Prod_Category,join_age,sub_delay,is_closed_date,0,1,2
0,Non Existing Client,NP_Client,University,Married,3.0,1.0,36.0,1.0,C,Sales,Owned,1.0,B,35.0,1.0,0.0,-3.0,1.0,-1.0
1,Existing Client,P_Client,University,Married,0.0,12.0,18.0,2.0,C,Sales,Parents,1.0,G,35.0,876.0,0.0,-3.0,1.0,0.0
2,Non Existing Client,NP_Client,University,Married,2.0,10.0,36.0,1.0,C,Sales,Owned,1.0,B,39.0,1.0,0.0,-3.0,1.0,-1.0
3,Existing Client,NP_Client,University,Married,3.0,3.0,36.0,1.0,C,Sales,New rent,1.0,L,29.0,13.0,1.0,-3.0,1.0,-1.0
4,Non Existing Client,NP_Client,University,Married,2.0,1.0,36.0,1.0,C,Sales,Owned,1.0,D,59.0,1.0,0.0,-3.0,1.0,-1.0
5,Existing Client,NP_Client,University,Married,0.0,28.0,60.0,2.0,C,Sales,Old rent,1.0,C,28.0,19.0,0.0,-3.0,1.0,-1.0
6,Non Existing Client,NP_Client,University,Married,0.0,10.0,36.0,1.0,C,Sales,Owned,1.0,B,32.0,11.0,0.0,-3.0,1.0,-1.0
7,Non Existing Client,NP_Client,University,Married,0.0,15.0,36.0,1.0,C,Sales,Owned,1.0,B,59.0,1.0,1.0,-3.0,1.0,-1.0
8,Existing Client,NP_Client,University,Single,0.0,0.0,500.0,3.0,P,Branch,Owned,1.0,E,27.0,4059.0,0.0,-3.0,1.0,-1.0
9,Existing Client,NP_Client,University,Married,4.0,35.0,87.0,2.0,C,Sales,Owned,1.0,L,48.0,6.0,1.0,-3.0,1.0,-1.0
10,Non Existing Client,NP_Client,University,Single,0.0,10.0,36.0,3.0,C,Sales,Owned,1.0,B,24.0,28.0,0.0,-3.0,1.0,-1.0
11,Non Existing Client,NP_Client,University,Married,0.0,10.0,18.0,2.0,C,Sales,Owned,2.0,B,52.0,14.0,0.0,-3.0,1.0,-1.0
12,Existing Client,P_Client,University,Single,0.0,2.0,29.0,4.0,C,Branch,Owned,1.0,G,26.0,1749.0,0.0,-3.0,1.0,0.0
13,Non Existing Client,NP_Client,University,Married,0.0,15.0,36.0,1.0,C,Sales,Owned,1.0,B,25.0,1.0,0.0,-3.0,1.0,-1.0
14,Non Existing Client,NP_Client,University,Married,0.0,1.0,36.0,1.0,G,Sales,Owned,1.0,C,37.0,4.0,0.0,-3.0,1.0,-1.0
15,Non Existing Client,NP_Client,University,Married,0.0,10.0,36.0,1.0,C,Sales,Owned,1.0,B,42.0,5.0,0.0,-3.0,1.0,-1.0
16,Non Existing Client,NP_Client,University,Married,0.0,15.0,30.0,1.0,C,Sales,Owned,1.0,B,38.0,9.0,0.0,-3.0,1.0,-1.0
17,Existing Client,NP_Client,University,Single,0.0,10.0,18.0,1.0,C,Sales,Owned,1.0,B,23.0,166.0,0.0,-3.0,1.0,-1.0
18,Non Existing Client,NP_Client,University,Married,2.0,1.0,36.0,1.0,C,Sales,Owned,1.0,B,30.0,3.0,1.0,-3.0,1.0,-1.0
19,Non Existing Client,NP_Client,University,Married,3.0,8.0,18.0,2.0,C,Sales,Owned,1.0,D,40.0,3.0,0.0,-3.0,1.0,-1.0
20,Non Existing Client,NP_Client,University,Married,0.0,15.0,30.0,1.0,C,Sales,Owned,1.0,B,62.0,21.0,0.0,-3.0,1.0,-1.0
21,Non Existing Client,NP_Client,University,Married,0.0,12.0,31.0,1.0,C,Sales,Owned,1.0,K,24.0,20.0,0.0,-3.0,1.0,-1.0
22,Non Existing Client,NP_Client,University,Single,0.0,27.0,26.0,6.0,C,Branch,Owned,1.0,K,27.0,15.0,1.0,-3.0,1.0,-1.0
23,Existing Client,P_Client,University,Married,3.0,10.0,24.0,3.0,C,Sales,Owned,1.0,G,34.0,1655.0,0.0,-3.0,1.0,0.0
24,Non Existing Client,NP_Client,University,Married,2.0,2.0,36.0,1.0,C,Sales,Owned,1.0,B,50.0,4.0,0.0,-3.0,1.0,-1.0
25,Non Existing Client,NP_Client,University,Married,0.0,1.0,36.0,1.0,C,Sales,Owned,1.0,B,64.0,1.0,0.0,-3.0,1.0,-1.0
26,Non Existing Client,NP_Client,University,Married,0.0,1.0,20.0,1.0,C,Sales,Owned,1.0,D,39.0,6.0,0.0,-3.0,1.0,-1.0
27,Non Existing Client,NP_Client,University,Single,0.0,4.0,18.0,4.0,C,Sales,Owned,1.0,B,22.0,4.0,0.0,-3.0,1.0,-1.0
28,Existing Client,NP_Client,University,Married,2.0,10.0,18.0,2.0,C,Sales,Owned,1.0,D,45.0,535.0,0.0,-3.0,1.0,-1.0
29,Non Existing Client,NP_Client,University,Married,0.0,22.0,18.0,2.0,C,Sales,Owned,1.0,B,59.0,1.0,0.0,-3.0,1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5350,Non Existing Client,NP_Client,University,Married,2.0,20.0,48.0,21.0,C,Branch,Owned,1.0,B,47.0,35.0,0.0,-3.0,1.0,-1.0
5351,Non Existing Client,NP_Client,University,Married,0.0,20.0,18.0,2.0,C,Branch,Owned,1.0,D,28.0,3.0,0.0,-3.0,1.0,0.0
5352,Existing Client,P_Client,University,Married,1.0,29.0,49.0,3.0,C,Branch,Owned,1.0,H,25.0,1149.0,0.0,-3.0,1.0,-1.0
5353,Existing Client,NP_Client,University,Married,3.0,22.0,18.0,2.0,C,Sales,Owned,1.0,D,29.0,1032.0,0.0,-3.0,1.0,-1.0
5354,Existing Client,NP_Client,University,Single,1.0,20.0,151.0,5.0,G,Branch,Owned,1.0,J,27.0,2232.0,0.0,-3.0,1.0,-1.0
5355,Existing Client,NP_Client,University,Married,1.0,20.0,300.0,10.0,P,Branch,Owned,1.0,E,37.0,2574.0,0.0,-3.0,1.0,-1.0
5356,Non Existing Client,NP_Client,University,Married,5.0,1.0,36.0,1.0,C,Sales,Owned,1.0,B,46.0,7.0,0.0,-3.0,1.0,-1.0
5357,Existing Client,P_Client,Master/PhD,Married,4.0,10.0,113.0,1.0,G,Branch,Owned,1.0,G,51.0,331.0,0.0,-3.0,1.0,-1.0
5358,Non Existing Client,NP_Client,University,Married,0.0,28.0,20.0,1.0,C,Sales,Old rent,1.0,B,57.0,1.0,0.0,-3.0,1.0,-1.0
5359,Existing Client,NP_Client,University,Married,0.0,9.0,1800.0,5.0,P,Branch,Owned,1.0,E,33.0,5413.0,0.0,-3.0,1.0,-1.0
5360,Non Existing Client,NP_Client,University,Single,0.0,1.0,20.0,1.0,C,Sales,Owned,1.0,B,25.0,8.0,0.0,-3.0,1.0,-1.0
5361,Non Existing Client,NP_Client,University,Married,0.0,15.0,36.0,1.0,C,Sales,Owned,1.0,B,56.0,1.0,0.0,-3.0,1.0,-1.0
5362,Non Existing Client,NP_Client,University,Married,0.0,1.0,36.0,1.0,C,Sales,Owned,1.0,B,32.0,0.0,0.0,-3.0,1.0,-1.0
5363,Existing Client,NP_Client,University,Married,0.0,15.0,30.0,1.0,C,Sales,Owned,1.0,B,49.0,1007.0,0.0,-3.0,1.0,0.0
5364,Existing Client,NP_Client,University,Married,2.0,30.0,100.0,1.0,P,Branch,Owned,1.0,E,47.0,5950.0,0.0,-3.0,1.0,-1.0
5365,Non Existing Client,NP_Client,University,Married,0.0,10.0,18.0,2.0,C,Sales,Owned,1.0,B,31.0,4.0,0.0,-3.0,1.0,-1.0
5366,Non Existing Client,NP_Client,Master/PhD,Married,0.0,1.0,20.0,1.0,C,Branch,Owned,2.0,C,49.0,1.0,1.0,-3.0,1.0,-1.0
5367,Non Existing Client,NP_Client,University,Married,2.0,10.0,50.0,10.0,C,Sales,Owned,1.0,B,48.0,1.0,0.0,-3.0,1.0,-1.0
5368,Non Existing Client,NP_Client,University,Married,1.0,10.0,36.0,3.0,C,Sales,Owned,1.0,B,35.0,1.0,0.0,-3.0,1.0,-1.0
5369,Existing Client,P_Client,University,Single,0.0,25.0,36.0,1.0,C,Sales,Owned,1.0,D,24.0,505.0,0.0,-3.0,1.0,-1.0
5370,Existing Client,NP_Client,University,Married,0.0,15.0,36.0,1.0,C,Sales,Owned,1.0,B,55.0,2120.0,0.0,-3.0,1.0,-1.0
5371,Existing Client,NP_Client,Master/PhD,Single,0.0,15.0,50.0,7.0,G,Sales,Owned,1.0,C,37.0,29.0,1.0,-3.0,1.0,-1.0
5372,Non Existing Client,NP_Client,University,Married,0.0,11.0,36.0,3.0,C,Sales,Owned,1.0,B,53.0,3.0,0.0,-3.0,1.0,-1.0
5373,Existing Client,NP_Client,University,Married,3.0,20.0,50.0,1.0,C,Sales,Owned,1.0,L,52.0,7.0,0.0,-3.0,1.0,-1.0
5374,Non Existing Client,NP_Client,University,Married,0.0,1.0,20.0,1.0,C,Sales,Owned,1.0,B,29.0,3.0,0.0,NaN,NaN,NaN
5375,Non Existing Client,NP_Client,University,Married,2.0,1.0,36.0,1.0,G,Sales,Owned,1.0,C,35.0,37.0,0.0,NaN,NaN,NaN
5376,Existing Client,NP_Client,University,Married,3.0,15.0,24.0,1.0,C,Sales,Owned,1.0,L,29.0,19.0,1.0,NaN,NaN,NaN
5377,Non Existing Client,NP_Client,University,Divorced,0.0,14.0,14.0,30.0,C,Branch,Old rent,1.0,B,61.0,1.0,1.0,NaN,NaN,NaN
5378,Non Existing Client,NP_Client,University,Married,1.0,1.0,36.0,1.0,G,Sales,Owned,1.0,C,29.0,4.0,0.0,NaN,NaN,NaN
5379,Non Existing Client,NP_Client,University,Married,0.0,15.0,30.0,1.0,C,Sales,Owned,1.0,B,29.0,8.0,0.0,NaN,NaN,NaN

In [6]:
X["Type_Of_Residence"].unique().tolist()

['Owned', 'Parents', 'New rent', 'Old rent', 'Company']

In [6]:
import category_encoders as ce

ModuleNotFoundError: No module named 'category_encoders'